#175 Replace `as-hash` with `hash-code-of`
objectionary/eo-collections pull request #177
Opened 2023-05-24 14:52 UTC by maxonfjvipon

Closes: #175

---

## PR-Codex overview
This PR replaces all `as-hash` objects with a new `hash-code-of` object in order to make `eo-runtime` independent of `eo-collections`.

### Detailed summary
- Replaces all `as-hash` objects with a new `hash-code-of` object in `multimap.eo` and `map.eo`.
- Adds `hash-code-of` alias to `multimap-tests.eo` and `hash-code-of.eo`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-05-24 16:47 UTC, maxonfjvipon commented
@volodya-lombrozo please have a look. This RP will unblock [this](https://github.com/objectionary/eo/issues/1724) issue

2023-05-25 10:25 UTC, volodya-lombrozo requested changes
@maxonfjvipon The only question is about the puzzle, maybe we need to remove its description from `map.eo` ?

2023-05-25 10:54 UTC, maxonfjvipon commented
@volodya-lombrozo sure, thanks
@yegor256 please merge this one

2023-05-25 11:24 UTC, volodya-lombrozo approved these changes

2023-05-29 09:42 UTC, maxonfjvipon commented
@yegor256 reminder

2023-05-29 09:43 UTC, yegor256 commented
@rultor merge

2023-05-29 09:45 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/32287-1566859367)

2023-05-29 09:55 UTC, merged

2023-05-29 09:56 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/32287-1566859367) (took me 10min)